[font]
size = 13

	[font.bold]
	family = "JetBrains Mono NL Nerd Font"
	style = "bold"

	[font.italic]
	family = "JetBrains Mono NL Nerd Font"
	style = "italic"

	[font.normal]
	family = "JetBrains Mono NL Nerd Font"
	style = "regular"

[window]
decorations = "none"
opacity = 0.8

	[window.padding]
	x = 5
	y = 5
